export const data = [
  {
    id:0,
    code: 'Q',
    nameFirst: 'Heater-1',
    urlFirst : 'https://s3.amazonaws.com/freecodecamp/drums/Heater-1.mp3',
    nameSecond : 'Chord-1',
    urlSecond : 'https://s3.amazonaws.com/freecodecamp/drums/Chord_1.mp3',
  },
  {
    id:1,
    code: 'W',
    nameFirst: 'Heater-2',
    urlFirst : 'https://s3.amazonaws.com/freecodecamp/drums/Heater-2.mp3',
    nameSecond : 'Chord-2',
    urlSecond : 'https://s3.amazonaws.com/freecodecamp/drums/Chord_2.mp3',
  },{
    id:2,
    code: 'E',
    nameFirst: 'Heater-3',
    urlFirst : 'https://s3.amazonaws.com/freecodecamp/drums/Heater-3.mp3',
    nameSecond : 'Chord-3',
    urlSecond : 'https://s3.amazonaws.com/freecodecamp/drums/Chord_3.mp3',
  },{
    id:3,
    code: 'A',
    nameFirst: 'Heater-4',
    urlFirst : 'https://s3.amazonaws.com/freecodecamp/drums/Heater-4_1.mp3',
    nameSecond : 'Shaker',
    urlSecond : 'https://s3.amazonaws.com/freecodecamp/drums/Give_us_a_light.mp3',
  },{
    id:4,
    code: 'S',
    nameFirst: 'Clap',
    urlFirst : 'https://s3.amazonaws.com/freecodecamp/drums/Heater-6.mp3',
    nameSecond : 'Open-HH',
    urlSecond : 'https://s3.amazonaws.com/freecodecamp/drums/Dry_Ohh.mp3',
  },{
    id:5,
    code: 'D',
    nameFirst: 'Open-HH',
    urlFirst : 'https://s3.amazonaws.com/freecodecamp/drums/Dsc_Oh.mp3',
    nameSecond : 'Closed-HH',
    urlSecond : 'https://s3.amazonaws.com/freecodecamp/drums/Bld_H1.mp3',
  },{
    id:6,
    code: 'Z',
    nameFirst: "Kick-n'-Hat",
    urlFirst : 'https://s3.amazonaws.com/freecodecamp/drums/Kick_n_Hat.mp3',
    nameSecond : 'Punchy-kick',
    urlSecond : 'https://s3.amazonaws.com/freecodecamp/drums/punchy_kick_1.mp3',
  },{
    id:7,
    code: 'X',
    nameFirst: 'Kick',
    urlFirst : 'https://s3.amazonaws.com/freecodecamp/drums/RP4_KICK_1.mp3',
    nameSecond : 'Side-Stick',
    urlSecond : 'https://s3.amazonaws.com/freecodecamp/drums/side_stick_1.mp3',
  },{
    id:8,
    code: 'C',
    nameFirst: 'Closed-HH',
    urlFirst : 'https://s3.amazonaws.com/freecodecamp/drums/Cev_H2.mp3',
    nameSecond : 'Snare',
    urlSecond : 'https://s3.amazonaws.com/freecodecamp/drums/Brk_Snr.mp3',
  },
]